Remove override on spring-core
Remove override on spring-core as spring-boot finally decided to join
the latest spring version as well, no longer causing the
NoClassDefFoundError for the ConcurrentLruCache implementation